theme: "PaperMod"

baseURL: "https://0x4b404ec.github.io/"
title: '0x4b404ec'
# é¡µæ•°
paginate: 5

# å¯ç”¨æœºå™¨äººTXT
enableRobotsTXT: true

# åˆ›å»ºæ—¶åŒ…æ‹¬è‰ç¨¿
buildDrafts: false
# 
buildFuture: false
# 
buildExpired: false

# googleåˆ†æ
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

# utteranc:
#     enable: true
#     repo: "0x4b404ec/0x4b404ec.github.io" 
#     issueTerm: "title"
#     theme: "github-light"  

params:
  # è®¾ç½®ç¯å¢ƒ
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  # ç½‘ç«™æ ‡é¢˜
  title: '0x4b404ec'
  # æ—¥æœŸæ ¼å¼åŒ–
  DateFormat: "2006-01-02"
  # RSS è¾“å‡ºå…¨æ–‡
  ShowFullTextinRSS: true   
  # ç½‘ç«™æè¿°
  description: "0x4b404ec's Blog"
  # ä¸»é¡µæ·»åŠ å…³é”®å­—
  keywords: [Blog, Unity, PaperMod]
  # æ˜¯å¦éšè—å…ƒå…ƒç´ ï¼Œdate, read-time, author and available-translations for page
  hidemeta: false
  # ä½œè€…
  author: "0x4b404ec" #author: ["Me", "You"] # multiple authors
  # opengraph, twitter-cardsçš„å›¾ç‰‡é“¾æ¥æˆ–è·¯å¾„
  images: ["<link or path of image for opengraph, twitter-cards>"]
  # é»˜è®¤ä¸»é¢˜
  defaultTheme: auto # auto, dark, light
  # ç¦ç”¨ä¸»é¢˜åˆ‡æ¢
  disableThemeToggle: false
  # æ–‡ç« æ˜¾ç¤ºé˜…è¯»æ—¶é—´
  ShowReadingTime: true
  # æ–‡ç« æœ€ä¸‹æ–¹æ˜¾ç¤ºåˆ†äº«æŒ‰é’®
  ShowShareButtons: false
  # åœ¨å•ä¸ªå¸–å­ä¸‹æ·»åŠ ä¸Šä¸€ä¸ª/ä¸‹ä¸€ä¸ªå¸–å­å»ºè®®
  ShowPostNavLinks: true
  # åœ¨æ ‡é¢˜ä¸Šæ–¹æ·»åŠ é¢åŒ…å±‘å¯¼èˆªï¼Œä»¥æ˜¾ç¤ºå­éƒ¨åˆ†å’Œä¸»é¡µå¯¼èˆª
  ShowBreadCrumbs: true
  # åœ¨ä»£ç å—ä¸­æ·»åŠ å¤åˆ¶æŒ‰é’®ä»¥å¤åˆ¶å…¶åŒ…å«çš„ä»£ç 
  ShowCodeCopyButtons: true
  # æ˜¾ç¤ºæ–‡ç« å­—æ•°
  ShowWordCount: true
  # æ˜¾ç¤ºRSSå›¾æ ‡
  ShowRssButtonInSectionTermList: true
  # ç¦ç”¨ç¬¬ä¸€ä¸ªå¸–å­çš„æ— å¡ç‰¹åˆ«å¤–è§‚
  disableSpecial1stPost: false
  # ç¦ç”¨è¿”å›æœ€ä¸Šæ–¹
  disableScrollToTop: false
  # æ˜¯å¦æ˜¾ç¤ºè¯„è®º
  comments: true
  # æ˜¯å¦éšè—æ‘˜è¦
  hideSummary: false
  # ä½¿ç”¨hugoç›®å½•
  UseHugoToc: true
  # æ˜¾ç¤ºç›®å½•
  showtoc: true
  # ç›®å½•å±•å¼€
  tocopen: true
  
  enableGitInfo: true

  # ä¸è’œå­æµè§ˆç»Ÿè®¡
  busuanzi:
    enable: true

  # ç½‘ç«™å›¾æ ‡
  assets:    
    # è®¾ç½®ç½‘ç«™å›¾æ ‡
    favicon: "https://avatars.githubusercontent.com/u/13428164?v=4"
    favicon16x16: "https://avatars.githubusercontent.com/u/13428164?v=4"
    favicon32x32: "https://avatars.githubusercontent.com/u/13428164?v=4"
    apple_touch_icon: "https://avatars.githubusercontent.com/u/13428164?v=4"
    safari_pinned_tab: "<link / abs url>"
    # æ˜¯å¦ä½¿ç”¨ Highlight.js åŠ è½½
    disableHLJS: true
    # èµ„æºçš„å­èµ„æºå®Œæ•´æ€§
    # disableFingerprinting: true

  label:
    # æ˜¾ç¤ºæ ‡é¢˜ä»¥å¤–çš„å…¶ä»–æ ‡ç­¾æ–‡æœ¬
    text: "0x4b404ec's Blog"
    # åœ¨æ ‡ç­¾ä¸­æ˜¾ç¤ºå¾½æ ‡å›¾åƒ
    icon: https://avatars.githubusercontent.com/u/13428164?v=4
    iconHeight: 35

  # ç®€ä»‹æ¨¡å¼ profile-mode---------------------------------
  profileMode:
    enabled: true # éœ€è¦æ˜¾å¼è®¾ç½®
    title: '0x4b404ec'
    subtitle: "A digital peasant."
    imageUrl: "https://avatars.githubusercontent.com/u/13428164?v=4"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Github_Avatar
    # buttons:
    #   - name: Posts
    #     url: posts
    #   - name: Tags
    #     url: tags

  # home-info mode---------------------------------
  # homeInfoParams:
  #   Title: "Hi!"
  #   Content: Welcome to my blog~ ğŸ°

  socialIcons:
    # - name: twitter
    #   url: "https://twitter.com/"
    - name: github
      url: "https://github.com/0x4b404ec/"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/7737930/a"    
    - name: bilibili
      url: "https://space.bilibili.com/14774685/"
    - name: steam
      url: "https://steamcommunity.com/profiles/76561198100031326/"

    # - name: email
    #   url: "wongze.dev@gmail.com"


  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  # å°é¢
  cover:    
    linkFullImages: false              # è¦æ‰“å¼€å…¨å°ºå¯¸çš„å°é¢å›¾åƒï¼Œè¯·ç‚¹å‡»å°é¢ - To open full size cover images on click on cover
    responsiveImages: true            # å¯ç”¨/ç¦ç”¨ç”Ÿæˆå“åº”æ€§å°é¢å›¾åƒ - To enable/disable generation of responsive cover images
    hidden: false                     # éšè—åœ¨ä»»ä½•åœ°æ–¹ï¼Œä½†ä¸æ˜¯åœ¨ç»“æ„åŒ–æ•°æ®ä¸­ - hide everywhere but not in structured data
    hiddenInList: false               # hide on list pages and home
    hiddenInSingle: false             # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    includeMatches: true
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
    

# æ·»åŠ èœå•é¡¹ï¼Œå®ƒå°†å‡ºç°åœ¨æ¯ä¸ªé¡µé¢çš„æ ‡é¢˜ä¸­ã€‚
# nameï¼šæ˜¾ç¤ºåç§° urlï¼šè·¯å¾„æˆ–å¤–éƒ¨é“¾æ¥ weightï¼šæƒé‡
menu:
  main:
    - identifier: about
      name: Me
      url: /about
      weight: 1
    - identifier: archive
      name: Archive
      url: /archives
      weight: 2
    - identifier: search
      name: Search
      url: /search
      weight: 3      
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: Theme Tutorials
      name: Theme.org
      url: https://github.com/adityatelange/hugo-PaperMod/wiki
      weight: 30


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true

markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai

# PaperMod uses Fuse.js Basic for seach functionality
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary


services:
  disqus:
    shortname: 